"""Backward-compatible dependency exports for presentation-layer modules.

Some routes still import authentication helpers from
``app.presentation.dependencies`` even though the canonical implementations are
located in ``app.dependencies``. Re-export them here so older imports continue
working without forcing a broad refactor.
"""

from app.dependencies import (
    get_current_user,
    get_user_repo,
    get_applicant_repo,
    get_applicant_result_repo,
    get_student_repo,
    get_course_repo,
    get_program_repo,
    get_payment_repo,
    get_fee_structure_repo,
    get_scholarship_repo,
    get_tenant_repo,
    get_grade_repo,
    get_registration_repo,
    get_academic_calendar_repo,
    get_application_fee_repo,
    get_attendance_repo,
    get_digital_signature_repo,
    get_auth_service,
    get_eligibility_engine,
    get_ranking_engine,
    get_allocation_engine,
    get_manual_results_service,
    get_waec_service,
    get_email_service,
    get_sms_service,
    get_s3_service,
    get_audit_repo,
    get_university_application_repo,
    get_identifier_sequence_repo,
    get_identifier_service,
    get_grade_calculator,
    require_roles,
)

__all__ = [
    "get_current_user",
    "get_user_repo",
    "get_applicant_repo",
    "get_applicant_result_repo",
    "get_student_repo",
    "get_course_repo",
    "get_program_repo",
    "get_payment_repo",
    "get_fee_structure_repo",
    "get_scholarship_repo",
    "get_tenant_repo",
    "get_grade_repo",
    "get_registration_repo",
    "get_academic_calendar_repo",
    "get_application_fee_repo",
    "get_attendance_repo",
    "get_digital_signature_repo",
    "get_auth_service",
    "get_eligibility_engine",
    "get_ranking_engine",
    "get_allocation_engine",
    "get_manual_results_service",
    "get_waec_service",
    "get_email_service",
    "get_sms_service",
    "get_s3_service",
    "get_audit_repo",
    "get_university_application_repo",
    "get_identifier_sequence_repo",
    "get_identifier_service",
    "get_grade_calculator",
    "require_roles",
]
